// <auto-generated />
using System;
using LibraryApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827200428_SeedDataToTables")]
    partial class SeedDataToTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryApp.Domain.Entities.Auteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Auteur");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Herbert",
                            Prenom = "Frank"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Asimov",
                            Prenom = "Isaac"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Gibson",
                            Prenom = "William"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Camus",
                            Prenom = "Albert"
                        });
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.AuteurLivre", b =>
                {
                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.HasKey("AuteurId", "LivreId");

                    b.HasIndex("LivreId");

                    b.ToTable("AuteurLivre");

                    b.HasData(
                        new
                        {
                            AuteurId = 1,
                            LivreId = 1
                        },
                        new
                        {
                            AuteurId = 1,
                            LivreId = 2
                        },
                        new
                        {
                            AuteurId = 2,
                            LivreId = 3
                        },
                        new
                        {
                            AuteurId = 3,
                            LivreId = 4
                        },
                        new
                        {
                            AuteurId = 4,
                            LivreId = 5
                        });
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Science-fiction"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Classique"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Cyberpunk"
                        });
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.CategorieLivre", b =>
                {
                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.HasKey("CategorieId", "LivreId");

                    b.HasIndex("LivreId");

                    b.ToTable("CategorieLivre");

                    b.HasData(
                        new
                        {
                            CategorieId = 1,
                            LivreId = 1
                        },
                        new
                        {
                            CategorieId = 1,
                            LivreId = 2
                        },
                        new
                        {
                            CategorieId = 1,
                            LivreId = 3
                        },
                        new
                        {
                            CategorieId = 1,
                            LivreId = 4
                        },
                        new
                        {
                            CategorieId = 3,
                            LivreId = 4
                        },
                        new
                        {
                            CategorieId = 2,
                            LivreId = 5
                        });
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.Editeur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Editeur");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Éditions Robert Laffont"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Éditions J'ai lu"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Éditions Gallimard"
                        });
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.Emprunt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEmprunt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRetour")
                        .HasColumnType("datetime2");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LivreId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Emprunt");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateEmprunt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRetour = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LivreId = 1,
                            UtilisateurId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateEmprunt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRetour = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LivreId = 1,
                            UtilisateurId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateEmprunt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LivreId = 3,
                            UtilisateurId = 1
                        });
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.Livre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EditeurId")
                        .HasColumnType("int");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("bit");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EditeurId");

                    b.ToTable("Livre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EditeurId = 1,
                            EstDisponible = true,
                            Titre = "Dune"
                        },
                        new
                        {
                            Id = 2,
                            EditeurId = 1,
                            EstDisponible = true,
                            Titre = "Le Messie de Dune"
                        },
                        new
                        {
                            Id = 3,
                            EditeurId = 2,
                            EstDisponible = false,
                            Titre = "Fondation"
                        },
                        new
                        {
                            Id = 4,
                            EditeurId = 2,
                            EstDisponible = true,
                            Titre = "Neuromancien"
                        },
                        new
                        {
                            Id = 5,
                            EditeurId = 3,
                            EstDisponible = true,
                            Titre = "L'Étranger"
                        });
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateur");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Courriel = "marc.tremblay@example.com",
                            Nom = "Marc Tremblay"
                        },
                        new
                        {
                            Id = 2,
                            Courriel = "julie.bouchard@example.com",
                            Nom = "Julie Bouchard"
                        });
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.AuteurLivre", b =>
                {
                    b.HasOne("LibraryApp.Domain.Entities.Auteur", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApp.Domain.Entities.Livre", "Livre")
                        .WithMany()
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.CategorieLivre", b =>
                {
                    b.HasOne("LibraryApp.Domain.Entities.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApp.Domain.Entities.Livre", "Livre")
                        .WithMany()
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.Emprunt", b =>
                {
                    b.HasOne("LibraryApp.Domain.Entities.Livre", "Livre")
                        .WithMany("Emprunts")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApp.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Emprunts")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.Livre", b =>
                {
                    b.HasOne("LibraryApp.Domain.Entities.Editeur", "Editeur")
                        .WithMany()
                        .HasForeignKey("EditeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editeur");
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.Livre", b =>
                {
                    b.Navigation("Emprunts");
                });

            modelBuilder.Entity("LibraryApp.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("Emprunts");
                });
#pragma warning restore 612, 618
        }
    }
}
